# Generated by Django 2.0 on 2017-12-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('facebook_id', models.CharField(default='', max_length=255)),
                ('avatar', models.CharField(default='', max_length=255)),
                ('cover', models.CharField(default='', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.CharField(default='', max_length=255)),
                ('key_word', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Value_Charater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(default='', max_length=255)),
                ('value_key', models.CharField(default='', max_length=255)),
                ('u_id', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
