# Generated by Django 2.0 on 2017-12-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20171227_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.BigIntegerField(auto_created=True, default=1),
            preserve_default=False,
        ),
    ]
